services:
  db:
    image: mysql:8.0
    networks:
      - custom_network
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flaskapp
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    image: flask-mysql-app:latest
    networks:
      - custom_network
    container_name: flask_app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    
volumes:
  db_data:
networks:
  custom_network:
    driver: bridge

